### ISSUE TITLE
snapshot_test:TestArchiveCommitlog.test_archive_commitlog

### ISSUE THREAD

**Issue by ptnapoleon** [riptano/cassandra-dtest#102]
https://issues.apache.org/jira/browse/CASSANDRA-8212 for 2.0

**Comment by ptnapoleon** [comment]
No longer failing on 2.0. Trunk problem still there, no response from devs yet.

**Comment by mshuler** [comment]
This test loads up a multitude of failures from a few tests, repeating the same errors "Error starting node1" and "Unexpected error in node1 node log: ['ERROR [main] ... CassandraDaemon.java: Detected unreadable sstables ..."

http://cassci.datastax.com/job/trunk_dtest/62/testReport/snapshot_test/
