### ISSUE TITLE
  counter_tests.py:TestCounters.upgrade_test

### ISSUE THREAD

**Issue by ptnapoleon** [riptano/cassandra-dtest#137]
This is hitting a commitlog error bug that is mentioned in 8428, but I don't think is related to the root issue I filed 8428 for. I have tried bisecting but I run into all sort of compaction errors and other commitlog errors. Trunk is showing different problems than 2.1.

The test may be doing something wrong, but there is most likely a C* issue here somewhere.

**Comment by ptnapoleon** [comment]
https://issues.apache.org/jira/browse/CASSANDRA-8564

**Comment by ptnapoleon** [comment]
8474 is fixed. Still waiting on 8564

**Comment by mshuler** [comment]
8564 is still open and this test still failing peridically in recent 2.1/trunk tests.
