### ISSUE TITLE
Should `topology_test.py` use nodetool for size calculation?

### ISSUE THREAD

**Issue by mambocab** [riptano/cassandra-dtest#190]
We changed [`simple_bootstrap_test`](https://github.com/riptano/cassandra-dtest/blob/master/bootstrap_test.py#L33) to use `nodetool info`, not `node.data_size` to calculate the load on each node (see #182 and #184). `topology_test.py` uses `data_size` in several places, like [here](https://github.com/riptano/cassandra-dtest/blob/master/topology_test.py#L45). Should that be switched over to use `nodetool` too?

**Comment by ptnapoleon** [comment]
I had no idea anywhere else used that. How about moving the implementation from your new get_size function, into the ccmlib to replace the existing `node.data_size()`?

**Comment by mambocab** [comment]
Can do. I'll need a little time to make it deal with different units than KB.

One limitation of this approach: I don't know about the load reported by `nodetool info`, but for other commands `nodetool`'s view of the load on a node is only updated every minute and a half. The [`nodetool info` docs](http://www.datastax.com/documentation/cassandra/2.1/cassandra/tools/toolsInfo.html) don't say anything about it, but, e.g., [the load data reported by `nodetool status` is only updated every 90 seconds](http://www.datastax.com/documentation/cassandra/2.1/cassandra/tools/toolsStatus.html).

**Comment by ptnapoleon** [comment]
From ccm's point of view, that's not a big deal. I do worry about the tests though. We could be checking stale data.

**Comment by mambocab** [comment]
It looks like the two use different methods to get load values. `info` uses `NodeProbe.getLoadString`:

https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/tools/NodeTool.java#L369
https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/service/StorageService.java#L2013

while, e.g., `status` uses `getLoadMap`:

https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/tools/NodeTool.java#L2130

which talks to `LoadBroadcaster` rather than `StorageMetrics`:

https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/service/StorageService.java#L2018

I've gone far enough down this rabbit hole for the moment. Who can we ask to find out if `nodetool info` gets fresh load information? If that information isn't accessible, I can dig further, or I can just give the method an optional argument to wait 90 seconds before running `nodetool info` (gross).

**Comment by ptnapoleon** [comment]
Ask in #cassandra on IRC

**Comment by mambocab** [comment]
Just for future reference: driftx on #cassandra tells me that the 90-second update time is for intra-node communication. `nodetool info` is asking for load information from the node itself and should be current.

**Comment by ptnapoleon** [comment]
Given that, seems we agree that to revert the PR that you made to bootstrap_test.py, and move that new code logic into ccmlib's node.py data_size()

**Comment by mambocab** [comment]
Yep. On it!

**Comment by ptnapoleon** [comment]
This is done in https://github.com/pcmanus/ccm/pull/247
