### ISSUE TITLE
cql_tests:TestCQL.composite_row_key_test

### ISSUE THREAD

**Issue by mambocab** [riptano/cassandra-dtest#191]
Fails on trunk:

```
CASSANDRA_DIR=~/cstar_src/cassandra nosetests -v cql_tests:TestCQL.composite_row_key_test
```

Passes on 2.0.12 and 2.1.3:
```
CASSANDRA_VERSION=2.0.12 nosetests -v cql_tests:TestCQL.composite_row_key_test  
CASSANDRA_VERSION=2.1.3 nosetests -v cql_tests:TestCQL.composite_row_key_test
```

The failure: `SELECT * FROM test WHERE k1 IN (0, 1) and k2 = 3` shouldn't be a valid query. 

How do I go about finding if there have been changes to CQL that would make it valid?

**Comment by ptnapoleon** [comment]
Check with @blerer.

**Comment by blerer** [comment]
Sorry, I forgot to push some local commits.
It should be fixed now.

**Comment by mambocab** [comment]
Sweet, thanks, @blerer.
