### ISSUE TITLE
Modify require decorator

### ISSUE THREAD

**Issue by ptnapoleon** [riptano/cassandra-dtest#238]
Currently the `require` decorator is just a glorified skip. To better serve our new testing model, `require` should be modified to accept the name of a git branch as an argument. This branch will correspond to the name of a git branch on a Cassandra fork. This will allow developers to commit new tests to dtest that will run in CI, but only against the fork with the code those tests are running against. Then, when the patch is merged, merging the tests is as simple as removing the decorator.

**Comment by mambocab** [comment]
closed by https://github.com/riptano/cassandra-dtest/commit/dcaf31e539bfafb611077702073aadeceec8f829
