### ISSUE TITLE
`__filter_errors` in `tearDown` TypeError

### ISSUE THREAD

**Issue by mambocab** [riptano/cassandra-dtest#246]
[When `__filter_errors` is called in `Tester.tearDown`](https://github.com/riptano/cassandra-dtest/blob/master/dtest.py#L430) it takes a list generated by `ccmlib.node.grep_log_for_errors` and [passes each element to `re.search` as the second argument](https://github.com/riptano/cassandra-dtest/blob/master/dtest.py#L487). Unfortunately, the elements generated by `grep_log_for_errors` [are lists](https://github.com/pcmanus/ccm/blob/master/ccmlib/node.py#L306), which leads to `TypeError`s when there are actually errors in the log. [This](https://gist.github.com/mambocab/233eb953c4e47236aa3c) is an example list, and [this](https://gist.github.com/mambocab/3311787a2a0b066d1625) is the resulting error from `nosetests`.

Am I understanding this correctly? If so, then `__filter_errors`, as called by `Tester.tearDown`, shouldn't have ever worked when there are actually errors.

**Comment by ptnapoleon** [comment]
This is working locally for me, and on cassci, even though it seems like it shouldn't.

**Comment by ptnapoleon** [comment]
Appears to definitely be windows only

**Comment by mambocab** [comment]
Reproduced on Linux. Used `UPGRADE_PATH=1_2:2_1 nosetests -x upgrade_through_versions_test.py:TestRandomPartitionerUpgrade` to trigger an ignored error. Output [here](https://gist.github.com/mambocab/afe95bcfb20ce9f22ad6#file-linux-txt-L215). 

That said, [here's](http://cassci.datastax.com/job/cassandra-2.1_dtest/lastCompletedBuild/testReport/counter_tests/TestCounters/upgrade_test/) an instance that Philip pointed out where it worked on Linux. No idea why.

**Comment by mambocab** [comment]
Fixed in #248. Closing.
