### ISSUE TITLE
sstablesplit_test failing

### ISSUE THREAD

**Issue by mshuler** [riptano/cassandra-dtest#262]
http://cassci.datastax.com/job/trunk_dtest/106/testReport/sstablesplit_test/TestSSTableSplit/split_test/
http://cassci.datastax.com/job/cassandra-2.1_dtest/71/testReport/sstablesplit_test/TestSSTableSplit/split_test/
http://cassci.datastax.com/job/cassandra-2.0_dtest/27/testReport/sstablesplit_test/TestSSTableSplit/split_test/

**Comment by ptnapoleon** [comment]
Fixed with a ccm commit 7216675d514d6048a0c31738d9687ef658fcff09
