### ISSUE TITLE
Turn require into a regex, not a string match

### ISSUE THREAD

**Issue by ptnapoleon** [riptano/cassandra-dtest#282]
This will help us use it for running on multiple branches.

@mambocab Thoughts?

**Comment by knifewine** [comment]
Seems like a nice idea. Downside is more rope. Might be nice to support simple match and regex both depending on how you invoke it.

**Comment by EnigmaCurry** [comment]
less rope version could be to have require(*args) so it could accept multiple strings. but I'm +1 to regex regardless if that's what we want.

**Comment by ptnapoleon** [comment]
Well a regex without any special modifiers is the equivalent of a simple match, no?

**Comment by ptnapoleon** [comment]
Also, for the use case of a dev working on CASSANDRA-ABC, which is 2.0 and they want to test 2.0, 2.1, 2.2, and 3.0.

They'll push branches `cassandra-abc-2.0`, `cassandra-abc-2.1`, etc. I'm sure they'd way rather call `require("casandra-abc.*")` than `require(args)` where `args = ["cassandra-abc-2.0", "cassandra-abc-2.1"....]`

**Comment by EnigmaCurry** [comment]
well, if it's *args it works both ways.

**Comment by knifewine** [comment]
The more I think about this, the less I have an opinion. I'd just say if the matching style changes the name should indicate that and it might save a few minutes of annoyance for a C* dev digging into dtest code.
