### ISSUE TITLE
make "connection" name consistent in codebase and across tests

### ISSUE THREAD

**Issue by knifewine** [riptano/cassandra-dtest#402]
We've got variables and methods with a soup of variations of session/connection/cursor.

We should try and settle on a single name, preferably the same one used in the cassandra python driver, and make it consistent across dtest.

I think some of this is vestigial from dbapi2 which offered somewhat different abstraction.

**Comment by ptnapoleon** [comment]
Yes, we should settle on using `session` as the default name for a connection.
