### ISSUE TITLE
upgrade tests need to handle CASSANDRA-10146

### ISSUE THREAD

**Issue by knifewine** [riptano/cassandra-dtest#486]
currently we default to protocol version 1 everywhere.

we need a little bit of code to choose protocol connection versions from those actually available on version V and V+1. It might be useful to abstract these into two strategies such as "reluctant" and "eager" where we use the minimal version that will work, or the maximal version, respectively.

**Comment by ptnapoleon** [comment]
We have code that does this in `dtest.py`'s `cql_connection`. We should extract that out into its own method and re-use it.
