### ISSUE TITLE
Refactor upgrade_tests

### ISSUE THREAD

**Issue by mambocab** [riptano/cassandra-dtest#487]
Merging #473 was a stopgap -- we wanted those tests running, but merging them wasn't ideal for maintainability. The tests merged there were copied and pasted from other tests in the codebase, then change to meet the needs of upgrade testing. Meanwhile, the tests from which they were copied changed a bit (if only stylistic changes). 

The refactor will go something like:

1. Write new base classes, one that preserves the old test behavior and one that upgrades the cluster in `prepare` as specified in `upgrade_tests.upgrade_base`
- Migrate the new test logic from the new tests into the old tests, deleting the copied tests as we go, ensuring that the test runs like it used to in the old test on one base class, and runs like the new test on the new base class

Luckily, step 2 can (should) be done test-by-test, in a bunch of smallish commits. Assuming all of those tests are copied and pasted (which may not be true), there will be about 170 tests to migrate:

```bash
$ nosetests 2>&1 --collect-only upgrade_tests -v | wc -l
172
```

One of the goals of this refactoring will be to separate out the upgrade logic from the logic of getting a session connected to each node in the cluster:

https://github.com/riptano/cassandra-dtest/pull/473#discussion_r37324041

**Comment by mambocab** [comment]
Just a note for later -- whatever replaces `do_upgrade` should give us access to the node itself, not just a session connected to it. In some tests, we need to know the version of the node we're connected to.

**Comment by ptnapoleon** [comment]
+1 on refactoring.
