### ISSUE TITLE
repair_compaction_test fails and leaves node running

### ISSUE THREAD

**Issue by mshuler** [riptano/cassandra-dtest#66]
This causes cascading errors in subsequent tests, i.e.:
http://cassci.datastax.com/job/cassandra-2.1_dtest/263/consoleFull

Running just this test:
http://aep.appspot.com/display/0LNkjCvTRVfA87oOIwyH9rhkXvc/

This test was disabled in conf/cassandra-2.1_test-select.cfg for runs on cassci, so when it's fixed up, please remove the test-select entry, too, and it will start running in jenkins.

**Comment by ptnapoleon** [comment]
@shawnkumar What's the status of this? Should this issue be closed? Is the test running? I see compaction_test is still disabled.

**Comment by mshuler** [comment]
It looks like repair_compaction_test.py was removed when incremental_repair_test.py was added - done.
`git show 6896b6b`
