### ISSUE TITLE
ERROR: Failure: ImportError (cannot import name SortedSet)

### ISSUE THREAD

**Issue by jasonstack** [riptano/cassandra-dtest#669]
Hi, I am unable to run dtest.

I am using python 2.7, ubuntu 14.04.

Here is the log:

--
ERROR: Failure: ImportError (cannot import name SortedSet)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/jasonstack/cassandra-dtest/cassandra-dtest/cqlsh_tests/cqlsh_copy_tests.py", line 14, in <module>
    from cassandra.util import SortedSet
ImportError: cannot import name SortedSet 

--

Thank you

**Comment by ptnapoleon** [comment]
What version of the python driver are you using?

**Comment by stef1927** [comment]
You need at least version 3.0rc1 of the python driver. For older versions,
you can just change SortedSet to all lowercase, sortedset.

On Wed, Nov 18, 2015 at 10:51 PM, Philip Thompson <notifications@github.com>
wrote:

> What version of the python driver are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/riptano/cassandra-dtest/issues/669#issuecomment-157738004>
> .
>



-- 


[image: datastax_logo.png] <http://www.datastax.com/>

Stefania Alborghetti

Apache Cassandra Software Engineer

|+852 6114 9265| stefania.alborghetti@datastax.com

**Comment by jasonstack** [comment]
Thank you.
I think the driver version is 2.7 , after change it to lowercase, it works.
