### ISSUE TITLE
SCUpgrade.upgrade_with_index_creation_test

### ISSUE THREAD

**Issue by ptnapoleon** [riptano/cassandra-dtest#97]
The test logic performs an upgrade from 2.0.x to the newest version. Once we are on 3.0, that will be an upgrade of two major versions, which will not work.

**Comment by ptnapoleon** [comment]
Also this uses the CLI, which isn't in trunk anymore.

**Comment by mambocab** [comment]
Relabeling as this is no longer applicable on trunk.

Looks like this [mostly passes](http://cassci.datastax.com/view/cassandra-2.1/job/cassandra-2.1_dtest/141/testReport/junit/upgrade_supercolumns_test/TestSCUpgrade/upgrade_with_index_creation_test/history/) on 2.1 now. It [flapped once](http://cassci.datastax.com/view/cassandra-2.1/job/cassandra-2.1_dtest/108/testReport/junit/upgrade_supercolumns_test/TestSCUpgrade/upgrade_with_index_creation_test/) a couple weks ago, but I'm not too concerned. Shall we close?

**Comment by ptnapoleon** [comment]
Go for it.
